// SERP'te kesilmemesi için ~60 karakteri aşmayan meta başlıklar; sayfadaki H1 (post.title) değişmez.
export const postMetaTitles: Record<string, string> = {
  "ceza-hukukunda-etkin-pismanlik": "Etkin Pişmanlık Nedir? Ceza İndirimi Şartları",
  "bosanma-davasinda-velayet": "Boşanmada Velayet: Mahkeme Hangi Kriterlere Bakar?",
  "kidem-tazminati-hesaplama-2026": "Kıdem Tazminatı Hakkı ve Hesaplama (2026 Rehberi)",
  "giydirilmis-ucret-kavrami": "Giydirilmiş Ücret Nedir? Kıdem ve İhbar Tazminatı",
  "ziynet-esyasi-davasi": "Düğünde Takılan Altın Kimindir? Ziynet Alacağı Davası",
  "ise-iade-davasi": "İşe İade Davası: Koşullar, Süre ve Süreç",
  "icra-takibi-ve-borca-itiraz": "İcra Takibi ve Borca İtiraz: Süreç ve Süreler",
  "tapu-iptali-ve-tescil-davasi": "Tapu İptali ve Tescil Davası: Şartlar ve Süreç",
  "kosullu-saliverilme-oranlari": "Koşullu Salıverilme Oranları ve İnfaz Süreleri",
  "ortakligin-giderilmesi-davasi": "Ortaklığın Giderilmesi (İzale-i Şüyu) Davası",
  "vasiyetname-nasil-duzenlenir": "Vasiyetname Nasıl Düzenlenir? Türleri ve Şartları",
  "muris-muvazaasi-nedir": "Muris Muvazaası Nedir? Tapu İptal Davası Hakkı",
  "bosanmada-nafaka-turleri": "Boşanmada Nafaka Türleri ve Hesaplama",
  "idari-islemin-iptali-davasi": "İdari İşlemin İptali Davası: Süre ve Şartlar",
  "nafakada-yuzde-kac-sorusu": "Nafaka Yüzde Kaç? Neden Sabit Oran Yoktur",
  "kiracinin-tahliye-sureci": "Kiracının Tahliye Süreci ve Kiraya Verenin Hakları",
  "kira-bedeli-tespit-ve-uyarlama-davasi": "Kira Tespit ve Uyarlama Davası Farkı",
  "tutukluluga-itiraz": "Tutukluluğa İtiraz Nasıl Yapılır?",
  "vergi-ihbarnamesine-itiraz-ve-uzlasma": "Vergi İhbarnamesine İtiraz ve Uzlaşma Yolları",
  "bosanma-sureci-bilinmesi-gerekenler": "Boşanma Süreci: Aşamalar, Belgeler ve Süre",
  "sozlesmeden-donme-ve-tazminat": "Sözleşmeden Dönme Hakkı Ne Zaman Kullanılır?",
  "miras-sakli-pay-tenkis": "Saklı Pay ve Tenkis Davası (Miras Hukuku)",
};
