import type { PseoDistrict } from "./types";

export const besiktas: PseoDistrict = {
  slug: "besiktas",
  name: "Beşiktaş",
  locative: "Beşiktaş'ta",
  ablative: "Beşiktaş'tan",
  genitive: "Beşiktaş'ın",
  dative: "Beşiktaş'a",
  courthouse: "İstanbul (Çağlayan) Adliyesi",
  taxOffice: "Beşiktaş Vergi Dairesi Müdürlüğü",
  neighborhoods: [
    "Sinanpaşa",
    "Abbasağa",
    "Akatlar",
    "Arnavutköy",
    "Balmumcu",
    "Bebek",
    "Cihannüma",
    "Dikilitaş",
    "Etiler",
    "Gayrettepe",
    "Konaklar",
    "Kuruçeşme",
    "Kültür",
    "Levazım",
    "Levent",
    "Mecidiye",
    "Muradiye",
    "Nispetiye",
    "Ortaköy",
    "Türkali",
    "Ulus",
    "Vişnezade",
    "Yıldız",
  ],
  transport: "Beşiktaş İskelesi üzerinden Üsküdar, Kadıköy, Kabataş ve Ortaköy hatlarına vapur bağlantısı bulunur; ilçe içi ulaşım büyük ölçüde otobüs hatlarıyla (22, 30D, 40T, 50L, DT1, U1, U2 ve benzeri) sağlanır.",
  officeNeighborhood: "Sinanpaşa",
  isOfficeLocation: true,
  publishedDate: "2026-07-11",
};
